version: '2'
services:
  homebanking-server:
    container_name: HomeBankingServer
    image: homebanking-server:latest
    restart: "no"
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - network-app
  coaf:
    container_name: CoafServer
    image: coaf:latest
    restart: "no"
    ports:
      - "8082:8082"
    expose:
      - "8082"
    networks:
      - network-app      
  cartao-credito:
    container_name: CartaoCreditoServer
    image: cartao-credito:latest
    restart: "no"
    ports:
      - "8083:8083"
    expose:
      - "8083"      
    networks:
      - network-app      
  api-gateway:
    container_name: ApiGatewayServer
    image: api-gateway:latest
    restart: "no"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - network-app      
networks:
  network-app:
