version: '2'
services:
  home-banking-server:
    container_name: HomeBankingServer
    image: homebanking-server:latest
    restart: always
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - network-app
  coaf-server:
    container_name: CoafServer
    image: coaf-server:latest
    restart: always
    ports:
      - "8082:8082"
    expose:
      - "8082"
    networks:
      - network-app      
  cartao-credito-server:
    container_name: CartaoCreditoServer
    image: cartaocredito-server:latest
    restart: always
    ports:
      - "8083:8083"
    expose:
      - "8083"      
    networks:
      - network-app      
  api-gateway-server:
    container_name: ApiGatewayServer
    image: api-gateway-server:latest
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - network-app      
networks:
  network-app: