version: '2'
services:
  executa-aplicacao:
    container_name: HomeBankingServer
    image: homebanking-server:latest
    restart: always
    ports:
      - "8081:8081"
    expose:
      - "8081"
  executa-aplicacao2:
    container_name: CoafServer
    image: coaf-server:latest
    restart: always
    ports:
      - "8082:8082"
    expose:
      - "8082"      
  executa-aplicacao3:
    container_name: CartaoCreditoServer
    image: cartaocredito-server:latest
    restart: always
    ports:
      - "8083:8083"
    expose:
      - "8083"      
  executa-aplicacao4:
    container_name: ApiGatewayServer
    image: api-gateway-server:latest
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"      